# Second Task Solution

In [ ]:
# Import the numpy package under the name np
import numpy as np

In [55]:
#Print the numpy version and the configuration
print(np.__version__)
print(np.show_config())

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SAM Chaudhry/anaconda3/env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SAM Chaudhry/anaconda3/env\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SAM Chaudhry/anaconda3/env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SAM Chaudhry/anaconda3/env\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SAM Chaudhry/anaconda3/env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SAM Chaudhry/anaconda3/env\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SAM Chaudhry/anaconda3/env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SAM 

In [64]:
# Create a null vector of size 10
vec = np.zeros(10).reshape(5,2)
print(vec)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [69]:
#How to find the memory size of any array
b = np.arange(16).reshape(4,4)
print(b)
print("The size of array is:",b.size)
print("The memory size of one array element is :", b.itemsize)
print("The memory size of numpy array element is :", b.size * b.itemsize)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
The size of array is: 16
The memory size of one array element is : 4
The memory size of numpy array element is : 64


In [71]:
#How to get the documentation of the numpy add function from the command line?
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [80]:
#Create a null vector of size 10 but the fifth value which is 1
b = np.zeros(10)
b[5] =1
print(b)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [82]:
#Create a vector with values ranging from 10 to 49
b = np.arange(10,49)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [93]:
#Reverse a vector (first element becomes last) 
print(b[49:0:-1])

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11]


In [96]:
# Create a 3x3 matrix with values ranging from 0 to 8
mat = np.arange(9).reshape(3,3)
print(mat)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [101]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
array_ind = np.array([1,2,0,0,4,0])
result = np.where(array_ind != 0 )
print(result)


(array([0, 1, 4], dtype=int64),)


In [117]:
#Create a 3x3 identity matrix 
mat = np.zeros(9).reshape(3,3)
mat[0,0]= 1
mat[1,1] = 1
mat[2,2] = 1
print("The Identity Matrix is here:\n", mat)

The Identity Matrix is here:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [122]:
#Create a 3x3x3 array with random values 
array_ran = np.random.randint(0,100,(3,3,3), dtype="i")
print("The '3D' array with random values is :\n ",array_ran)

The '3D' array with random values is :
  [[[80 15 16]
  [94 27 21]
  [15 21 65]]

 [[70 25 40]
  [55 96 68]
  [22 50 80]]

 [[ 8 52 75]
  [28  9 26]
  [44 91  4]]]


In [126]:
 #Create a 10x10 array with random values and find the minimum and maximum values
array_ran = np.random.randint(0,1000,(10,10), dtype="int64")
print("The '2D' array with random values is :\n ",array_ran)
maxi = array_ran.max()
mini = array_ran.min()
print("The maximum value in the given array is: ", maxi)
print("The minimum value in the given array is: ", mini)



The '2D' array with random values is :
  [[955 253 793 599 862 378 881 672 698 711]
 [329 290 602 575   5 866 313 410  86 369]
 [107 432 788  32 972 653  76 353 253 206]
 [871 944 243 249 263 801  55 601 984 162]
 [566 650 487 743 556 841 140 717 277 300]
 [549 847 372 726 139 316 734 608  73 260]
 [468 519 294 797 443 141  95 654 842 136]
 [744 227 681 656 715 415 830  69 645 963]
 [133 250 348  34 210 941 948 798 608 379]
 [489 306 642 823 473 331 623 610 335 920]]
The maximum value in the given array is:  984
The minimum value in the given array is:  5


In [151]:
#Create a random vector of size 30 and find the mean value
vec = np.random.randint(0,10,(30), dtype="int32")
print(vec)
vec = np.mean(vec)
print(vec)

[2 0 7 2 4 3 4 0 6 2 4 8 8 1 3 8 5 7 7 8 0 3 2 8 5 0 0 6 8 9]
4.333333333333333


In [226]:
#Create a 2d array with 1 on the border and 0 inside
arr_zero = np.ones(16).reshape(4,4)
arr_zero[1:-1, 1:-1] = 0
print(arr_zero)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


# 